baseURL = "/"
languageCode = "en-us"
title = "Star Wars: Insurgency MUSH"

[menu]
  [[menu.main]]
    title = "Theme Information"
    identifier = "theme"
    url = "/theme"
    weight = 2
  [[menu.main]]
    title = "Systems"
    identifier = "systems"
    url = "/systems"
    weight = 3
  [[menu.main]]
    title = "Game Mechanics"
    identifier = "mechanics"
    url = "/mechanics"
    weight = 4
  [[menu.main]]
    title = "Roster"
    identifier = "characters"
    url = "/characters"
    weight = 5
  [[menu.main]]
    title = "Logs"
    identifier = "logs"
    url = "/logs"
    weight = 7
  [[menu.main]]
    title = "Resources"
    identifier = "resources"
    url = "/resources"
    weight = 7
